apiVersion: v1
kind: Pod
metadata:
  name: palindrome
  labels:
    app: palindrome
spec:
  containers:
    - name: palindrome
      image: ghcr.io/rahmanrafi/qswf-swe
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: palindrome-service
spec:
  type: NodePort
  selector:
    app: palindrome
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
