apiVersion: v1
kind: Service
metadata:
  name: {{ include "palindrome.fullname" . }}-service
  labels:
    {{- include "palindrome.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    {{- include "palindrome.selectorLabels" . | nindent 4 }}
